### ISSUE TITLE
Building hugo

### ISSUE THREAD

**Issue by mttmccb** [stephlocke/battleofthebeards#3]
Getting one bug with it, seems like it might be missing some files? or maybe I'm missing a step?

```
Started building sites ...
=============================================================
Your rendered home page is blank: /index.html is zero-length
 * Did you specify a theme on the command-line or in your
   "config.toml" file?  (Current theme: "hugo-agency-theme")
 * For more debugging information, run "hugo -v"
=============================================================
ERROR: 2017/01/06 19:53:07 template.go:142: Unable to render [partials/footer.html theme/partials/footer.html]
ERROR: 2017/01/06 19:53:07 template.go:143: Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [partials/footer.html theme/partials/footer.html]
ERROR: 2017/01/06 19:53:07 template.go:142: Unable to render [partials/js.html theme/partials/js.html]
ERROR: 2017/01/06 19:53:07 template.go:143: Expecting to find a template in either the theme/layouts or /layouts in one of the following relative locations [partials/js.html theme/partials/js.html]
```

**Comment by mttmccb** [comment]
Looks like I need to add this step to the README

```
$ cd themes
$ git clone https://github.com/digitalcraftsman/hugo-agency-theme
```

Although the site CSS still looks a bit broken.

**Comment by stephlocke** [comment]
I haven't had chance to do anything but "works on my machine" - any help resolving CSS (and improving it for stuff like my quickly hacked together static page CSS) and automating things on commits would be super duper handy

**Comment by stephlocke** [comment]
http://speps.github.io/articles/hugo-setup/

**Comment by mttmccb** [comment]
I'm not sure what I'm doing wrong but I found a way to watch the public directory instead, for some reason using the localhost:1313 address means loads of broken links :(

**Comment by stephlocke** [comment]
hmm, `hugo server -w`?

**Comment by mttmccb** [comment]
nah, that didn't work, I think I found a possible cause, seems like something must have been updated, I'll drop in a pull request, hopefully it won't break it your side :)

**Comment by mttmccb** [comment]
Just putting it here for reference, it came down to breaking changes in the theme so you need to checkout a particular commit.

```shell
cd themes
git clone https://github.com/digitalcraftsman/hugo-agency-theme
cd hugo-agency-theme
git checkout 4f504cf
```
