### ISSUE TITLE
Revise About section format

### ISSUE THREAD

**Issue by stephlocke** [stephlocke/battleofthebeards#6]
The centre align block of text is hard to read! Perhaps a two column layout with left align or something?

Changes can be applied to [layouts/partials/services.html](https://github.com/stephlocke/battleofthebeards/blob/master/layouts/partials/services.html) and [static/css/beardy.css](https://github.com/stephlocke/battleofthebeards/blob/master/static/css/beardy.css)

A few things worth doing

- [ ] Making the text larger
- [ ] Combining or cutting down the content to the key bits of info

**Comment by mttmccb** [comment]
I've looked at this a few times and I think it just need to be shorter and to the point, a bit like the card on eventbrite... I've updated it a little to simplify it.

**Comment by stephlocke** [comment]
Moved About us to a static page and left key points
